import "./globals.css";
import Header from "./views/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="px-4 py-8 w-full min-h-screen bg-slate-100">{children}</main>
      </body>
    </html>
  );
}
